### ISSUE TITLE
How to pass custom command, execute it and then close the app?

### ISSUE THREAD

**Issue by klugier** [ismail-yilmaz/Terminal#2]
Hello Oblivion,

I just want to write simple terminal application using yours TerminalCtrl. I just want to pass the command to app with TerminalCtrl via "-c" parameter for example "./SimpleTerminalApp -c "bash my-script.sh"". After that TerminalCtrl should launch this command from the shell. When the bash script ends the application should close itself. How to do it?

I am currently working on Flatpak for U++ and I just need to spawn terminal at the first launch to install dependencies via terminal.

Klugier

**Comment by ismail-yilmaz** [comment]
> Hello Oblivion,
> 
> I just want to write simple terminal application using yours TerminalCtrl. I just want to pass the command to app with TerminalCtrl via "-c" parameter for example "./SimpleTerminalApp -c "bash my-script.sh"". After that TerminalCtrl should launch this command from the shell. When the bash script ends the application should close itself. How to do it?
> 
> I am currently working on Flatpak for U++ and I just need to spawn terminal at the first launch to install dependencies via terminal.
> 
> Klugier

Basically this should work (variant 1):

```

#include <Terminal/Terminal.h>
#include <PtyProcess/PtyProcess.h>

using namespace Upp;

struct TerminalExample : TopWindow {
	void Run(const String& cmd)
	{
		PtyProcess   p;
		TerminalCtrl t;
		SetRect(t.GetStdSize());
		Sizeable().Zoomable().CenterScreen().Add(t.SizePos());
		t.WhenTitle  = [=, &cmd](String s) { Title(s);   };
		t.WhenOutput = [&](String s)       { p.Write(s); };
		t.WhenResize = [&]()               { p.SetSize(t.GetPageSize()); };
		p.Start(cmd, Environment(), GetHomeDirectory());
		OpenMain();
		while(IsOpen()) { // Window stays open even if the pty process is exited...
			Ctrl::ProcessEvents();
			String s = p.Get();
			int l = s.GetLength();
			t.WriteUtf8(s);
			Sleep(l >= 1024 ? 1024 * 10 / l : 10); // Scale to workload. For real-life performance...
		}
		p.Kill();
	}
};

GUI_APP_MAIN
{
	TerminalExample().Run("/bin/bash ./myscript.sh");
//	TerminalExample().Run("/bin/bash -c top");
}

```

Variant 2:

```

#include <Terminal/Terminal.h>
#include <PtyProcess/PtyProcess.h>

using namespace Upp;

struct TerminalExample : TopWindow {
	void Run(const String& cmd)
	{
		PtyProcess   p;
		TerminalCtrl t;
		SetRect(t.GetStdSize());
		Sizeable().Zoomable().CenterScreen().Add(t.SizePos());
		t.WhenTitle  = [=, &cmd](String s) { Title(s);   };
		t.WhenOutput = [&](String s)       { p.Write(s); };
		t.WhenResize = [&]()               { p.SetSize(t.GetPageSize()); };
		p.Start(cmd, Environment(), GetHomeDirectory());
		bool fin = false;
		while(IsOpen()) { // // Window stays open even if the pty process is exited...
			Ctrl::ProcessEvents();
			String s = p.Get();
			int l = s.GetLength();
			if(!p.IsRunning() && !l && !fin) {
				t.Echo(String() << "----------Script executed. Exit code: " << p.GetExitCode());
				fin = true;
			}
			else
				t.WriteUtf8(s);
			Sleep(l >= 1024 ? 1024 * 10 / l : 10); // Scale to workload. For real-life performance...
		}
		p.Kill();
	}
};

GUI_APP_MAIN
{
	TerminalExample().Run("/bin/bash ./myscript.sh");
//	TerminalExample().Run("/bin/bash -c top");
}

```

Of course, you need to add the command line reader, which is  trivial, so I didn't add it to the example. The basics are these. You can also autoclose the window after pty exits, as you can also check for it (p.IsRunning()).

By the way, I highly suggest updating the PtyProcess to latest revision, as I've caught a bug which caused bash to fail on script execution with infamous "resource unavailable" error.  It is fixed now.

Feel free to ask any questions about terminal, I'll be happy to help.

Best regards,
