### ISSUE TITLE
New Release - 2023.2

### ISSUE THREAD

**Issue by klugier** [ismail-yilmaz/Terminal#3]
Hello Oblivion,

I am currently working on Flathubed version of TheIDE and UppTerm will be integrated part of the package. One of the requiremenets to publish package is that it won't use any unrelease code. You can read more about it on (https://docs.flathub.org/docs/for-app-authors/requirements).

It means that I will need to replace this statmenet (org.ultimatepp.TheIDE.yml):
```
      - type: git
        url: https://github.com/ismail-yilmaz/Terminal
        commit: d1e74fbc0428f5d09319dacb464fa38e60a9a032
        dest: 3p/Terminal
```

With something like:
```
      - type: archive
        url: hhttps://github.com/ismail-yilmaz/Terminal/releases/download/2023.2/2023.2.tar.gz
        sha256: 23793a363a140139728a30cc050c35287d6ff97ee03125d62f8ad8acf06e40af
        dest: 3p/Terminal
```

Here is my working flathub repo if you want to learn more https://github.com/klugier/flathub/tree/upp. Still there are a lot of thinks to do, but the main functionality works. It means that full flatpaked ide can compile any upp apps.

Klugier

**Comment by ismail-yilmaz** [comment]
@klugier 

I see. TerminalCtrl is already mature and battle tested, so I see no reason to not publish it "officially". I will do it asap.

(By the way, right now I am finalizing the initial release of Bobcat, a fully-fledged terminal emulator that is also meant to serve as a  tech demo for U++)

**Comment by ismail-yilmaz** [comment]
@klugier 

Here you go! TerminalCtrl 2023.2 is officialy [released](https://github.com/ismail-yilmaz/Terminal/releases/tag/2023.2)

Cheers!

**Comment by klugier** [comment]
Thank you!
