### ISSUE TITLE
New release 2024.1

### ISSUE THREAD

**Issue by klugier** [ismail-yilmaz/Terminal#5]
I will build new flatpak for U++ 2024.1. It would be good to use newer TerminalCtrl there. Of course, if possible. I will be also fine with 2023.2.

**Comment by ismail-yilmaz** [comment]
> I will build new flatpak for U++ 2024.1. It would be good to use newer TerminalCtrl there. Of course, if possible. I will be also fine with 2023.2.

I am preparing TerminalCtrl just for that. It has many new cool features and bug fixes (a big release). But release notes and final tests require a couple of days, can you allow me that time?

**Comment by klugier** [comment]
Sure, no problem on my side. Thank you!

**Comment by ismail-yilmaz** [comment]
> Sure, no problem on my side. Thank you!

Here you go, TerminalCtrl [2025.1](https://github.com/ismail-yilmaz/Terminal/releases/tag/2025.1).

**Comment by klugier** [comment]
Thanks!
